darkMode@linuxedo: add support to XDG Desktop Portal
linuxmint/cinnamon-spices-applets pull request #5023
Opened 2023-09-03 21:30 UTC by Wilfison

Add support to XDG Desktop Portal.

XDG Desktop Portal support was added to all supported desktops (Cinnamon, MATE and Xfce). Among other things this brings a global dark mode setting.

This setting only affects applications which support dark mode.

2023-09-03 21:53 UTC, rcalixte commented on darkMode@linuxedo.com/README.md
> +- Set 3, 2023
Small typo here.

2023-09-03 21:53 UTC, rcalixte requested changes

2023-09-03 21:53 UTC, rcalixte commented on darkMode@linuxedo.com/README.md
> +- Set 3, 2023
Typo here.

2023-09-03 21:53 UTC, rcalixte commented
cc @slgobinath

2023-09-04 18:18 UTC, Wilfison commented on darkMode@linuxedo.com/README.md
> +* Set 3, 2023
Correct, my mistake in the translation

2023-09-04 19:06 UTC, rcalixte approved these changes

2023-09-04 19:14 UTC, rcalixte commented
@Wilfison Have you tested this on versions before Cinnamon 5.8? I'm not sure if this change needs to be implemented in a versioned structure or not. I'll let @slgobinath chime in too before merging.

2023-09-08 00:06 UTC, rcalixte commented
> @rcalixte You were right, I added a version check for the minimum supported to be 5.8

You should make use of directory versioning, similar to all of the other applets. This will remove the need for a conditional in the code. You can take the code from before this PR and move it to a 3.0 directory and then put the code for the new PR in a 5.8 directory. This simplifies the code for future maintenance. If you need a hand, I can help with this. Just say the word! Thanks!

2023-09-09 17:35 UTC, Wilfison commented
@rcalixte Thanks for the feedback. I will follow your instruction.

Do you think it's better for me to close this pull request with multiple commits and create a new one with just a single commit?

2023-09-09 17:37 UTC, rcalixte commented
> Do you think it's better for me to close this pull request with multiple commits and create a new one with just a single commit?

It's fine. We can squash and merge so that the final merge will just be one commit.

2023-09-09 18:57 UTC, rcalixte commented
@Wilfison I went ahead and pushed a few commits to clean things up a bit. We should be good to merge now. Thanks for your contribution!

2023-09-09 18:58 UTC, merged

2024-01-25 18:27 UTC, sudoshindo commented
@slgobinath @rcalixte @wilfison 

Hello.

I made a suggestion over at the spices applet page, but I just want to make sure the comment is seen.

Here is a copy of what I said there:

**Suggestion:**

Make the background specific/explicit instead of random. Setting up a light/dark wallpaper pair is kind of a hassle because you have to make 2 directories containing only 1 image each. It might be better if you get rid of the "random selection" part of the code so that the wallpaper files are easier to manage for users.

It would allow us to have a `/wallpapers/sunset` dir that contains `sunset-dark.png` and `sunset-light.png` instead of doing something like `/wallpapers/dark/sunset.png` and `/wallpapers/light/sunset.png` and we could even avoid grouping the pairs into subdirectories if we wanted to since we could specify the exact image paths.