Add shadowsocks-switch@Klavionik
linuxmint/cinnamon-spices-applets pull request #5029
Opened 2023-09-11 22:01 UTC by Klavionik

Hello! 

Long story short: I've found using Shadowsocks under Linux Mint rather hassled and decided to try and implement a simple switch applet. I hope you will find it a useful addition.

2023-09-11 23:34 UTC, rcalixte approved these changes

2023-09-11 23:36 UTC, rcalixte requested changes

2023-09-11 23:36 UTC, rcalixte commented on shadowsocks-switch@Klavionik/files/shadowsocks-switch@Klavionik/icon.png
@Klavionik The icon needs to be square dimensions and it is currently 62 x 64. If you can fix this, we can merge the new applet. Thank you!

2023-09-12 06:00 UTC, Klavionik commented on shadowsocks-switch@Klavionik/files/shadowsocks-switch@Klavionik/icon.png
Sorry for the trouble. Fixed the icon and updated the commit.

2023-09-12 07:24 UTC, Klavionik commented on shadowsocks-switch@Klavionik/files/shadowsocks-switch@Klavionik/icon.png
I also took a chance to update the screenshot. :)

2023-09-12 10:59 UTC, rcalixte commented on shadowsocks-switch@Klavionik/files/shadowsocks-switch@Klavionik/icon.png
No need to apologize! Thanks for your contribution!

2023-09-12 11:01 UTC, rcalixte approved these changes

2023-09-12 11:01 UTC, merged