Sensors@claudiux: add support for Nvidia SMI temperatures
linuxmint/cinnamon-spices-applets pull request #6482
Opened 2024-10-11 16:00 UTC by JEleniel

Use the nvidia-smi tool (https://developer.nvidia.com/system-management-interface) to read GPU temperatures 

Spice author: @claudiux 
References: #6078

2024-10-11 17:04 UTC, claudiux requested changes

2024-10-11 17:04 UTC, claudiux commented on Sensors@claudiux/files/Sensors@claudiux/applet.js
> +    this.nvidiaLoopId = Mainloop.timeout_add(this.interval * 1000, () => this.reap_nvidia_smi());
The line 405 seems useless and contains an error.
`this.reap_nvidia_smi()` sould be `this.reaper.reap_nvidia_smi()` and a loop already exists calling `this.reap_sensors()` which calls `this.reaper.reap_nvidia_smi()`.

Please remove this.nvidiaLoopId from this applet.

2024-10-11 17:07 UTC, claudiux commented
@JEleniel Thanks for the care. However, some changes are necessary.

2024-10-11 23:51 UTC, claudiux approved these changes

2024-10-11 23:53 UTC, merged

2024-10-28 01:47 UTC, FibroJedi commented
@claudiux  At the risk of seeming dumb, have these changes gone out to the world? Only asking because my version of the applet isn't pulling in the NVIDIA temperatures per nvidia-smi or I can't find the option for it. I'm on 3.8.2 per the About dialog. (I didn't want to create a new issue in case there was no issue. Thanks!

2024-10-28 18:33 UTC, claudiux commented
Ping @JEleniel

2024-10-28 20:07 UTC, JEleniel commented
Hello @FibroJedi, I am the author of the Nvidia code. The changes are in 3.8.2. 

The *nvidia-smi* tool is part of the Nvidia closed source drivers, only supports ["NVIDIA's Tesla, Quadro, GRID and GeForce devices from Fermi and higher architecture families"](https://docs.nvidia.com/deploy/nvidia-smi/index.html), and the applet requires version 550.107.02 or higher.

If you have a compatible GPU and the closed source drivers installed, please post the output of `nvidia-smi -L`. You can also try the `Windows-L` key combination to bring up the Cinnamon debugger (melange) or look in the `~/.xsession-errors` log for errors - search for "Nvidia SMI".

2024-10-28 20:25 UTC, FibroJedi commented
> Hello @FibroJedi, I am the author of the Nvidia code. The changes are in 3.8.2.
> 
> The _nvidia-smi_ tool is part of the Nvidia closed source drivers, only supports ["NVIDIA's Tesla, Quadro, GRID and GeForce devices from Fermi and higher architecture families"](https://docs.nvidia.com/deploy/nvidia-smi/index.html), and the applet requires version 550.107.02 or higher.
> 
> If you have a compatible GPU and the closed source drivers installed, please post the output of `nvidia-smi -L`. You can also try the `Windows-L` key combination to bring up the Cinnamon debugger (melange) or look in the `~/.xsession-errors` log for errors - search for "Nvidia SMI".

I have closed source drivers and nvidia-smi installed (and works). Result of `nvidia-smi -L`
> GPU 0: NVIDIA GeForce RTX 3050

But I'm currently on version 535 Drivers. I was going to upgrade them today anyway. I've just had issues in the past with upgrading the drivers, then the system not rebooting properly. I'll see if I can get up to 550 without incident then check the applet.

Thanks for the info - and sorry if that was somewhere in the documentation!

2024-10-28 22:01 UTC, FibroJedi commented
Now I have, thankfully, successfully upgraded to driver-550, the NVIDIA option in Sensors is showing. Thank you!

2024-10-28 22:51 UTC, JEleniel commented
I'm glad you were able to get it working. I should add that information to the documentation.